name: Publish to NuGet

on:
  workflow_dispatch:

jobs:
  build-test-pack-publish:
    name: Build, Test, Pack and Publish
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore --nologo
    
    - name: Build
      run: dotnet build --configuration Release --no-restore --nologo
    
    - name: Test
      run: dotnet test --configuration Release --no-build --nologo
    
    - name: Pack
      run: dotnet pack src/HttpHammer/HttpHammer.csproj --configuration Release --no-build --nologo --output nupkgs
    
    - name: Get version from Nerdbank.GitVersioning
      id: nbgv
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
    
    - name: Publish to NuGet
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    
    - name: Create and push version tag
      if: success()
      run: |
        git tag -a v${{ steps.nbgv.outputs.SimpleVersion }} -m "Release v${{ steps.nbgv.outputs.SimpleVersion }}"
        git push origin v${{ steps.nbgv.outputs.SimpleVersion }}